language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armabi-v7a
    
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1
    
script: ./gradlew test
