language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armabi-v7a
    
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1
    - android-23
    
script: ./gradlew test
